### ISSUE TITLE
Manually self update via HTTP request

### ISSUE THREAD

**Issue by ghost** [periph/gohci#5]
I feel it woudl be useful for the gohci to be self updating. It just looks to look at a URL for new binaries.
There are many libs that do this for golang running as a service.

But i first wanted to ask if this is useful.

I am doing alot of frotnend and hardware work and it woudl make it easier since some of the machines are not local but in other peopels labs, and so when any work happens on gohci it woudl be great for it to also update itself.

anyway would be great to hear others thoughts on this proposal.

**Comment by gedw99** [comment]
hey @maruel. thanks for respnding on slack !

No rush, but please send me links to explain why systemd, launchd and windows service is enough to update the actual gohci binary when we change it.

My use case is machines i have no control over. I send them an SD Card or a binary (for desktops)  and they install it, and i get an email with the IP address as described here with efe: https://github.com/periph/bootstrap#efe

**Comment by maruel** [comment]
The current setup code is:

- linux/systemd: https://github.com/periph/gohci/blob/master/systemd/setup.sh
- macOS/launchd: https://github.com/periph/gohci/blob/master/macos/gohci.plist
- Windows; just a small doc: https://github.com/periph/gohci/blob/master/CONFIG.md#windows

gohci handles updates by:
- keep a lock when any task is enqueued or running
- listen to file change to its own executable
- when the executable or config file is updated, try to take the lock (to ensure there's no task lost) and exit
  - https://github.com/periph/gohci/blob/master/cmd/gohci-worker/server.go#L49
- it's up to systemd/launchd/taskmgr to restart the gohci process

This is designed to reduce the risk of a bad push from hosing the workers. It is were the gohci-worker executable to handle the self-update itself, a bad push could require manual intervention.

**Comment by maruel** [comment]
Can be achieved via https://github.com/jpillora/overseer

**Comment by gedw99** [comment]
:)
