### ISSUE TITLE
Enable polling based work (vs webhook)

### ISSUE THREAD

**Issue by ghost** [periph/gohci#6]
would like to have a polling based system.
https://github.com/periph/gohci/blob/master/cmd/gohci-worker/server.go#L119

**Comment by maruel** [comment]
For non-internet accessible workers, it would have to fallback to polling based mechanism. This issue is about adding this to gohci. Ironically this mean adding back the project level configuration in gohci.yml that was recently ripped off.

**Comment by gedw99** [comment]
Was this ever done ? 

I have to admit that its quite useful for NATed devices with only a dynamic domain name assigned to them.

The other way of course is to run a public http reverse proxy. then each agent gets a session. Basically like ngrok.

**Comment by maruel** [comment]
No I did not work on that. I do use a reverse proxy + ddclient to keep the dynamic dsn up.
The caddy configuration looks like https://github.com/periph/website/blob/master/resources/ci.periph.io.conf#L36
